### PR TITLE
(MCOP-609) Fix package data provider to pass correct action

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
It looks like `spec/data/package_data_spec.rb` will need to be updated to expect `:status` instead of `'status'`.

**Comment by treydock** [comment]
@MikaelSmith spec test updated

**Comment by ripienaar** [comment]
👍

**Comment by MikaelSmith** [comment]
Thanks so much for fixing this up!

**Pull request merged**
